#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Define custom keycodes. Start the first one at the right range
enum custom_keycodes {
    KC_COMMSCLN = SAFE_RANGE, // For KC_COMMA and KC_SCOLON
    KC_DOTSCLN // For KC_DOT and KC_SCOLON
};

// Define keymap. Generated by QMK Configurator.
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_P7, KC_P8, KC_P9, KC_PAST, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINS, KC_BSPC, KC_P4, KC_P5, KC_P6, KC_PMNS, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_QUOT, KC_ENT, KC_P1, KC_P2, KC_P3, KC_PPLS, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMSCLN, KC_DOTSCLN, KC_SLSH, KC_RSFT, KC_NLCK, KC_P0, KC_PDOT, KC_PENT, KC_ESC, KC_LGUI, KC_LALT, LT(1,KC_SPC), KC_NO, LT(1,KC_SPC), KC_RALT, KC_RCTL, KC_BSLS, KC_DEL),
	[1] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_EQL, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCTL, KC_LBRC, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_UP, KC_DOWN, KC_LEFT, KC_RGHT, KC_NO, KC_ENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(2), KC_TILD, KC_NO, KC_NO, KC_NO, KC_NO, KC_HOME, KC_END, KC_LT, KC_GT, KC_NO, MO(2), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ESC, KC_LGUI, KC_LALT, LT(3,KC_SPC), KC_NO, LT(3,KC_SPC), KC_RALT, KC_RCTL, KC_NO, KC_DEL),
	[2] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_TAB), KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_PLUS, RSFT(KC_BSPC), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_LCTL), KC_LCBR, KC_RCBR, KC_NO, KC_NO, KC_NO, RSFT(KC_UP), RSFT(KC_DOWN), RSFT(KC_LEFT), RSFT(KC_RGHT), KC_NO, RSFT(KC_ENT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_GRV, KC_NO, KC_NO, KC_NO, KC_NO, RSFT(KC_HOME), RSFT(KC_END), KC_LT, KC_GT, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_ESC), LSFT(KC_LGUI), LSFT(KC_LALT), KC_TRNS, KC_NO, KC_TRNS, RSFT(KC_RALT), RSFT(KC_RCTL), KC_NO, RSFT(KC_DEL)),
	[3] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCTL, KC_VOLD, KC_MUTE, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_PGUP, KC_PGDN, KC_NO, KC_NO, KC_ENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LSFT, RESET, DEBUG, KC_INS, KC_PAUS, KC_NO, KC_HOME, KC_END, KC_NO, KC_NO, KC_NO, KC_RSFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ESC, KC_LGUI, KC_LALT, KC_TRNS, KC_NO, KC_TRNS, KC_RALT, KC_RCTL, KC_PSCR, KC_DEL)
};

// Define what happens when one of the custom keycodes is sent.
// The process_record_user() function is is called each time a key is pressed.
bool process_record_user(uint16_t keycode, keyrecord_t *record)
{
    switch (keycode)
    {
      case KC_COMMSCLN:
        if (record->event.pressed) // When a key with this keycode is pressed...
        {
          if (keyboard_report->mods & MOD_BIT(KC_LSFT) || keyboard_report->mods & MOD_BIT(KC_RSFT)) 
          {
            register_code(KC_SCLN); // If shift is down, use the ;: keycode.
          } else {
            register_code(KC_COMM); // If shift isn't down, use the ,< keycode.
          }
        } else {
          unregister_code(KC_SCLN);
          unregister_code(KC_COMM);
        }
        return false; // Stop further processing of this keypress.
      case KC_DOTSCLN:
        if (record->event.pressed) 
        {
          if (keyboard_report->mods & MOD_BIT(KC_LSFT) || keyboard_report->mods & MOD_BIT(KC_RSFT))
          {
            register_code(KC_SCLN); // If shift is down, use the ;: keycode.
          } else {
            register_code(KC_DOT); // If shift isn't down, use the .> keycode.
          }
        } else {
          unregister_code(KC_SCLN); 
          unregister_code(KC_DOT);
        }
        return false; // Stop furhter processing of this keypress.
      default:
        return true; // Continue processing other keypresses normally.
    }
}

